name: Docker Delete Image

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      registry:
        required: true
        type: string
      tag:
        required: false
        type: string
    secrets:
      token:
        required: true

jobs:
  delete_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: docker - image delete
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          owner: ${{ github.repository_owner }}
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.token }}
          tag: ${{ inputs.tag }}
