name: Docker Build

on:
  workflow_call:
    outputs:
      tags:
        description: "Docker tags built"
        value: ${{ jobs.build.outputs.tags }}
    inputs:
      username:
        required: true
        type: string
      registry:
        required: true
        type: string
      image:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.docker_metadata.outputs.tags }}

    steps:
      - id: tolower_image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ inputs.image }}

      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login
        id: docker_login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: docker - extract metadata
        id: docker_metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ steps.tolower_image.outputs.lowercase }}
          flavor: |
            latest=false
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and cache
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.docker_metadata.outputs.tags }}
          labels: ${{ steps.docker_metadata.outputs.labels }}
          cache-from: |
            type=registry,ref=${{ steps.docker_metadata.outputs.tags }}
            type=registry,ref=${{ inputs.registry }}/${{ steps.tolower_image.outputs.lowercase }}:${{ github.event.repository.default_branch }}
          cache-to: type=inline 

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}
 
      - name: docker - composer run test
        shell: bash
        run: |
          docker run --rm --env-file .env.test ${{ needs.build.outputs.tags }} composer run test

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker - login
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: docker - composer run check
        shell: bash
        run: |
          docker run --rm --env-file .env.test ${{ needs.build.outputs.tags }} composer run check
