name: CI/CD

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
    types: [ opened ,closed ,synchronize ,reopened ]

jobs:
  ci:
    if: ((github.event.action != 'closed' && github.event.pull_request.merged != true))
    uses: ./.github/workflows/docker_build.yml
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      image: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  cd:
    if: github.ref == 'refs/heads/develop'
    needs: ci
    uses: ./.github/workflows/waypoint.yml
    with:
      workspace: develop
      tag: develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      encodedString:  ${{ secrets.MEDV2_STAGE_KUBE_CONFIG_B64 }}
      WAYPOINT_SERVER_TOKEN: ${{ secrets.WAYPOINT_SERVER_TOKEN }}
      WAYPOINT_SERVER_ADDR: ${{ secrets.WAYPOINT_SERVER_ADDR }}
      WAYPOINT_SERVER_TLS: ${{ secrets.WAYPOINT_SERVER_TLS }}
      WAYPOINT_SERVER_TLS_SKIP_VERIFY: ${{ secrets.WAYPOINT_SERVER_TLS_SKIP_VERIFY }}

  release:
    needs: [ci, cd]
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/semantic_release.yml
    secrets:
      token: ${{ secrets.SMARTMEDBOT_PAT }}

  cleanup:
    if: ((github.event.action == 'closed' || github.event.pull_request.merged == true))
    uses: ./.github/workflows/docker_delete.yml
    with:
      REGISTRY: ghcr.io
      username: ${{ github.actor }}
      TAG: pr-${{ github.event.number }}
    secrets:
      token: ${{ secrets.SMARTMEDBOT_PAT }}
